coloured heading
codepharm/git pull request #6
Opened 2022-09-08 17:31 UTC by nettle790

added a colour to the heading.

2022-09-10 12:49 UTC, codeTrackLift requested changes
Please follow notes as outlined in Issue #4 

create styles folder
name the stylesheet styles.css and place in the styles folder
add a background
add a header with some intro text

2022-09-10 17:02 UTC, nettle790 commented
issue #4 

please review the changes

styles folder created within which styles.css file has been created which is linked to index.html.

applied a background colour and an  image.

provided a header

2022-09-10 17:07 UTC, codeTrackLift commented
Nice job w the changes, please see suggestions/comments.  Let me know w any questions, thanks!

2022-09-10 17:13 UTC, codeTrackLift commented
@nettle790 also friendly reminder about project tracking and keeping the project board updated.

Please review the [Project Board](https://github.com/orgs/codepharm/projects/6/views/1), you'll see that I've updated the related issue status by moving it to the In Review swim lane, and linked this as the related PR.

I've also assigned this to you as the PR `assignee`, and added this to the project board (see right sidebar of this PR).  These practices are how we stay synchronized in an asynchronous work environment. 

Hope that makes sense, let me know with any questions.  Thanks!

2022-09-11 04:04 UTC, nettle790 commented
Thanks.

Sent from my iPhone

> On 10-Sep-2022, at 10:43 PM, Pete Chu ***@***.***> wrote:
> 
> ﻿
> @nettle790 also friendly reminder about project tracking and keeping the project board updated.
> 
> Please review the Project Board, you'll see that I've updated the related issue status by moving it to the In Review swim lane, and linked this as the related PR.
> 
> I've also assigned this to you as the PR assignee, and added this to the project board (see right sidebar of this PR). These practices are how we stay synchronized in an asynchronous work environment.
> 
> Hope that makes sense, let me know with any questions. Thanks!
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.

2022-09-23 14:04 UTC, nettle790 commented on styles/styles.css
> +  background-image: url("./images/athens0.jpeg");
url file path changed to ./

2022-09-24 18:14 UTC, codeTrackLift reviewed
Please move `images` folder out of `styles` folder, such that it is a sibling to the `styles` folder and is located at `~/images` with `~` being `root`.

2022-09-24 18:14 UTC, codeTrackLift commented on index.html
> +  <link rel="stylesheet" href="styles/styles.css" type="text/css">
suggest to prefix url w `./`

is the `type="text/css"` necessary?

2022-09-24 18:14 UTC, codeTrackLift commented on index.html
> +  <h2>ATHENA the patron goddess of Greece<h2><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></br>
Any reason for the `<br>`s?

If extra space is needed, suggest to apply styling via added stylesheet.

2022-09-24 18:14 UTC, codeTrackLift commented on styles/styles.css
> +  background-image: url("athens0.jpeg");
suggest to create an `images` folder in project `root` then move image there and re-route.

also suggest to prefix url with `./` similar to href

2022-09-24 18:14 UTC, codeTrackLift commented on index.html
> +  <link rel="stylesheet" href="styles/styles.css" type="text/css">
@nettle790

2022-09-24 18:14 UTC, codeTrackLift commented on index.html
> +  <h2>ATHENA the patron goddess of Greece<h2><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></br>
@nettle790

2022-09-24 18:14 UTC, codeTrackLift commented on styles/styles.css
> +  background-image: url("athens0.jpeg");
@nettle790

2022-09-24 18:14 UTC, codeTrackLift commented on index.html
> +  <link rel="stylesheet" href="styles/styles.css" type="text/css">
Please prefix href with `./` in line 9

2022-09-25 05:24 UTC, nettle790 commented
please cite one good reason as to why the images folder should be in the root directory??

2022-09-25 15:14 UTC, codeTrackLift commented
> please cite one good reason as to why the images folder should be in the root directory??

The images should not be under `styles` as they are not styles. To clarify, I meant the project root, not your local root.

2022-09-27 17:38 UTC, nettle790 commented
I know what a sibling folder and a tilde is meant for but I am not able to implement it practically.please review to note whether the folder structure is what it should be.

2022-09-27 18:34 UTC, codeTrackLift commented
```
.    
├── ...
├── styles                 
│   └── global.css     
├── images
│   └── filename.img        
├── index.html     
└── README.md
```

Please remove the `root` follow the suggested folder structure above.

2022-10-05 11:19 UTC, nettle790 commented
please review and send me links to  any docs on relative file paths.so far I have been using the text editor right click relative file path option.this is a bit confusing.

2022-10-06 12:36 UTC, codeTrackLift approved these changes

2022-10-06 12:36 UTC, codeTrackLift commented on styles/styles.css
> +  background-image: url("./images/athens0.jpeg");
Please move the `images` folder out of the `styles` folder.  See [this comment](https://github.com/codepharm/git/pull/6#pullrequestreview-1103154662)

2022-10-06 12:36 UTC, codeTrackLift commented on index.html
> +  <link rel="stylesheet" href="base/styles/styles.css" type="text/css">
Thanks for making the file structure updates.  I think we may need to update the `href` here as well.  Suggest to replace `base` with `./`

2022-10-06 12:37 UTC, merged

2022-10-07 11:59 UTC, nettle790 commented
please review the new file structure.is it the right way to create it?
<img width="475" alt="Screenshot 2022-10-07 at 5 18 03 PM" src="https://user-images.githubusercontent.com/73188561/194547284-5bcdccf5-92e8-49be-a596-613ecf1732ce.png">

for example in the above file path could you please  reply as to which is the:

1. root directory
2. home directory 
3. project root.

2022-10-07 12:09 UTC, codeTrackLift commented
It looks fine, but anything beyond the project folder structure is up to you as that's on your local machine.  

For the changes we did here, I would just propose to keep file type and folder names aligned, an example is [this file structure model](https://github.com/codepharm/git/pull/6#issuecomment-1259900459).

2022-10-08 14:28 UTC, nettle790 commented
thanks so much.Learning filepaths now  which is important though you left one question unanswered.
Please check why index.html is conflicting in new pull request. I had deleted it and added it again in the project folder.should not be causing an issue though????

2022-10-08 14:41 UTC, codeTrackLift commented
It looks like a `project` directory was added and the content in `index.html` was deleted [here](https://github.com/codepharm/git/pull/11/files)

This "git practice" repo is intended for folks to practice `git` commands.

Feel free to continue building things out and take your project as far as you'd like to do, but it's probably not necessary to to merge in this 'practice' repo.  I'm going to close #11 to resolve the conflict, let me know with any questions/concerns.

2022-10-30 13:58 UTC, nettle790 commented
sorry ,was practicing PR's.